name: Update GitHub Profile Page
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  gadpp_job:
    runs-on: ubuntu-latest
    name: Update GitHub Profile Page
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: GADPP
        uses: ./
        id: gadpp
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-username: 'isaquebrother90'
          user-email: 'improgramcode@gmail.com'
